import React, { useMemo, useState } from 'react';
import {
  Activity, AlarmClock, ArrowLeft, BarChart3, Bell, Building2, CalendarDays,
  Check, ChevronLeft, ChevronDown, ClipboardCheck, Clock3, FileHeart, FileText,
  HeartPulse, Home, LineChart, MapPin, Menu, MessageCircle, MoreHorizontal,
  Phone, Pill, Plus, Search, Settings, ShieldCheck, Sparkles, Stethoscope,
  TestTube2, UserRound, UsersRound, Video, X, Zap, LogOut, LayoutDashboard,
  CalendarCheck, ClipboardList, Megaphone, UserCog, Star, Upload, Download
} from 'lucide-react';

const doctors = [
  { id:1, name:'د. سلمى الشريف', specialty:'طب القلب والأوعية', exp:'12 سنة خبرة', rating:'4.9', image:'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=700&q=80', color:'#d7f0ed' },
  { id:2, name:'د. عمر منصور', specialty:'الباطنة والجهاز الهضمي', exp:'9 سنوات خبرة', rating:'4.8', image:'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=700&q=80', color:'#e6effb' },
  { id:3, name:'د. مريم جمال', specialty:'الجلدية والتجميل', exp:'8 سنوات خبرة', rating:'4.9', image:'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=700&q=80', color:'#fcece7' },
];

const appointments = [
  {time:'09:00', patient:'أحمد حسن', type:'متابعة', doctor:'د. سلمى الشريف', status:'حضر', avatar:'أح'},
  {time:'09:30', patient:'نور علي', type:'كشف جديد', doctor:'د. عمر منصور', status:'في الانتظار', avatar:'نع'},
  {time:'10:15', patient:'منى محمود', type:'متابعة تحاليل', doctor:'د. سلمى الشريف', status:'مؤكد', avatar:'مم'},
  {time:'11:00', patient:'يوسف خالد', type:'كشف جديد', doctor:'د. مريم جمال', status:'مؤكد', avatar:'يخ'},
  {time:'12:30', patient:'سارة سامح', type:'استشارة', doctor:'د. عمر منصور', status:'لم يؤكد', avatar:'سس'},
];

const patients = [
  {name:'أحمد حسن', id:'CL-2041', age:46, phone:'010 2468 1357', condition:'ضغط مرتفع', last:'اليوم', next:'28 سبتمبر', risk:'متوسط'},
  {name:'منى محمود', id:'CL-1998', age:39, phone:'012 4490 1288', condition:'متابعة قلب', last:'15 سبتمبر', next:'1 أكتوبر', risk:'منخفض'},
  {name:'نور علي', id:'CL-2114', age:31, phone:'011 7622 9031', condition:'آلام معدة', last:'اليوم', next:'غير محدد', risk:'منخفض'},
  {name:'سارة سامح', id:'CL-1840', age:52, phone:'010 8831 6672', condition:'سكري نوع 2', last:'9 سبتمبر', next:'23 سبتمبر', risk:'مرتفع'},
];

const IconBadge = ({children, tone='teal'}) => <span className={`icon-badge ${tone}`}>{children}</span>;
const Logo = ({compact=false}) => <div className="logo"><span className="logo-mark"><HeartPulse size={25}/></span>{!compact && <span><b>كلينيكا</b><small>رعاية متصلة</small></span>}</div>;

function PublicHeader({onOpen}) {
  return <header className="public-header">
    <Logo />
    <nav><a href="#features">المميزات</a><a href="#doctors">الأطباء</a><a href="#marketing">التسويق</a><a href="#about">عن المنصة</a></nav>
    <div className="header-actions"><button className="ghost-btn" onClick={()=>onOpen('patient')}>دخول المريض</button><button className="primary-btn" onClick={()=>onOpen('dashboard')}>عرض النظام <ArrowLeft size={17}/></button></div>
  </header>
}

function Landing({onOpen}) {
  const [booking,setBooking]=useState(false);
  return <div className="landing">
    <PublicHeader onOpen={onOpen}/>
    <main>
      <section className="hero">
        <div className="hero-copy">
          <span className="eyebrow"><Sparkles size={15}/> منصة طبية متكاملة للعيادات والمراكز</span>
          <h1>إدارة أذكى للعيادة.<br/><em>رعاية أقرب</em> للمريض.</h1>
          <p>من أول حجز الموعد حتى المتابعة بعد الزيارة، كل تفاصيل العيادة والمريض في مكان واحد، بتجربة عربية سهلة وآمنة.</p>
          <div className="hero-actions"><button className="primary-btn big" onClick={()=>onOpen('dashboard')}>استكشف النسخة التجريبية <ArrowLeft size={19}/></button><button className="play-btn" onClick={()=>setBooking(true)}><span><CalendarCheck size={20}/></span>احجز موعدًا تجريبيًا</button></div>
          <div className="trust-row"><div><b>+2,400</b><span>موعد مُدار</span></div><i></i><div><b>98%</b><span>رضا المرضى</span></div><i></i><div><b>24/7</b><span>وصول آمن</span></div></div>
        </div>
        <div className="hero-visual">
          <div className="hero-photo"><img src="https://images.unsplash.com/photo-1666887360983-83ef0f9b71e1?auto=format&fit=crop&w=1200&q=85" alt="طبيبة تتحدث مع مريضة"/></div>
          <div className="float-card appointment-card"><div className="calendar-mini"><span>سبتمبر</span><b>17</b></div><div><strong>موعدك القادم</strong><p>د. سلمى الشريف · 10:30 ص</p></div><Check size={18}/></div>
          <div className="float-card pulse-card"><span className="pulse-icon"><Activity/></span><div><small>مؤشر المتابعة</small><b>مستقر <span>+8%</span></b></div></div>
          <div className="medical-grid"></div>
        </div>
      </section>

      <section className="logos-strip"><span>مصمم ليناسب</span><b><Stethoscope/>الدكتور المستقل</b><b><Building2/>العيادات</b><b><HeartPulse/>المراكز الطبية</b><b><UsersRound/>فرق الرعاية</b></section>

      <section className="section features-section" id="features">
        <div className="section-heading"><span className="section-kicker">منظومة واحدة</span><h2>كل ما تحتاجه لإدارة رحلة المريض</h2><p>أدوات عملية مبنية حول سير العمل الحقيقي داخل العيادة، وليست مجرد برنامج مواعيد.</p></div>
        <div className="feature-grid">
          {[
            [CalendarDays,'حجز ومواعيد ذكية','جداول للدكاترة والفروع، قوائم انتظار، تذكير تلقائي وإعادة جدولة.','blue'],
            [FileHeart,'ملف طبي متكامل','زيارات، تشخيصات، وصفات، تحاليل، أشعة وحساسية في خط زمني واضح.','teal'],
            [Activity,'متابعة وخطة علاج','قياسات وأعراض ومهام وتنبيهات توضح للطبيب تطور الحالة بين الزيارات.','coral'],
            [MessageCircle,'تواصل منظم','محادثات داخل النظام، مرفقات، رسائل مهمة وسياسة واضحة لفترات الرد.','purple'],
            [ShieldCheck,'صلاحيات وسجل نشاط','صلاحيات لكل دور وسجل يوضح من شاهد أو عدّل بيانات المريض.','green'],
            [BarChart3,'تقارير تشغيلية','الحضور والإلغاء ومصادر الحجز وأداء الفروع والدكاترة في لوحات سهلة.','orange']
          ].map(([I,t,d,c])=><article className="feature-card" key={t}><IconBadge tone={c}><I/></IconBadge><h3>{t}</h3><p>{d}</p><a onClick={()=>onOpen('dashboard')}>عرض داخل النظام <ChevronLeft size={16}/></a></article>)}
        </div>
      </section>

      <section className="journey-section">
        <div className="journey-copy"><span className="section-kicker light">رحلة متصلة</span><h2>المريض لا يضيع بين الزيارة والمتابعة</h2><p>كل خطوة مسجلة، وكل تعليمات واضحة، والطبيب يرى الصورة كاملة قبل اتخاذ القرار.</p><button className="white-btn" onClick={()=>onOpen('patient')}>استكشف بوابة المريض <ArrowLeft size={17}/></button></div>
        <div className="journey-flow">{[['01','اختيار الطبيب'],['02','حجز الموعد'],['03','تسجيل الزيارة'],['04','بدء المتابعة']].map((x,i)=><React.Fragment key={x[0]}><div className="journey-step"><b>{x[0]}</b><span>{x[1]}</span></div>{i<3&&<div className="flow-line"></div>}</React.Fragment>)}</div>
      </section>

      <section className="section doctors-section" id="doctors">
        <div className="section-heading row"><div><span className="section-kicker">فريق طبي موثوق</span><h2>اختار التخصص والطبيب المناسب</h2></div><button className="outline-btn">عرض كل الأطباء <ArrowLeft size={17}/></button></div>
        <div className="doctor-grid">{doctors.map(d=><article className="doctor-card" key={d.id}><div className="doctor-img" style={{background:d.color}}><img src={d.image}/><span className="available"><i></i>متاح اليوم</span></div><div className="doctor-info"><div className="rating"><Star size={15} fill="currentColor"/>{d.rating}</div><h3>{d.name}</h3><p>{d.specialty}</p><small>{d.exp}</small><button onClick={()=>setBooking(true)}>احجز موعدًا</button></div></article>)}</div>
      </section>

      <section className="marketing-band" id="marketing"><div className="marketing-art"><div className="video-frame"><img src="https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80"/><span><Video/></span></div><div className="reel-card"><b>04</b><span>فيديوهات شهريًا</span><div className="reel-bars"><i></i><i></i><i></i></div></div></div><div className="marketing-copy"><span className="section-kicker">خدمة اختيارية منفصلة</span><h2>حضور رقمي يليق بخبرة الطبيب</h2><p>نحوّل معرفة الطبيب إلى محتوى طبي واضح يبني الثقة ويجيب عن أسئلة المرضى، بخطة شهرية قابلة للقياس.</p><ul><li><Check/>خطة محتوى لكل تخصص</li><li><Check/>أفكار وسيناريوهات طبية</li><li><Check/>تصوير ومونتاج حتى 4 فيديوهات</li><li><Check/>جدول نشر ومراجعة الأداء</li></ul><small>خدمة التسويق مستقلة عن اشتراك النظام وتُنفذ حسب الاتفاق.</small></div></section>
    </main>
    <footer><div><Logo/><p>منصة عربية لإدارة الرعاية الطبية من الحجز إلى المتابعة.</p></div><div><b>المنتج</b><a>المميزات</a><a>الدكاترة</a><a>بوابة المريض</a></div><div><b>للعيادات</b><a>طلب عرض</a><a>خطة التسويق</a><a>الدعم</a></div><div><b>تواصل معنا</b><a><Phone size={15}/> 0100 123 4567</a><a>hello@clinica.demo</a></div></footer>
    {booking&&<BookingModal onClose={()=>setBooking(false)}/>} 
  </div>
}

function BookingModal({onClose}){const [done,setDone]=useState(false);return <div className="modal-backdrop"><div className="booking-modal">{done?<div className="success-state"><span><Check/></span><h2>تم تأكيد طلب الحجز</h2><p>موعدك يوم السبت 19 سبتمبر، 10:30 صباحًا. الدفع داخل العيادة.</p><button className="primary-btn" onClick={onClose}>تم</button></div>:<><div className="modal-head"><div><span className="section-kicker">حجز سريع</span><h2>اختر الموعد المناسب</h2></div><button className="icon-btn" onClick={onClose}><X/></button></div><label>الطبيب<select><option>د. سلمى الشريف · قلب وأوعية</option><option>د. عمر منصور · باطنة</option><option>د. مريم جمال · جلدية</option></select></label><div className="date-row">{['الخميس 17','السبت 19','الأحد 20'].map((d,i)=><button className={i===1?'selected':''}>{d}<small>سبتمبر</small></button>)}</div><div className="time-grid">{['09:00','09:30','10:30','11:00','12:30','01:00'].map((t,i)=><button className={i===2?'selected':''}>{t}</button>)}</div><div className="payment-note"><ShieldCheck/><span><b>لا يوجد دفع أونلاين</b><small>الدفع يتم مباشرة داخل العيادة.</small></span></div><button className="primary-btn full" onClick={()=>setDone(true)}>تأكيد طلب الحجز</button></>}</div></div>}

const navItems=[
  ['dashboard','نظرة عامة',LayoutDashboard],['appointments','المواعيد',CalendarDays],['patients','المرضى',UsersRound],['patient-file','ملف المريض',FileHeart],['followup','المتابعة',Activity],['messages','الرسائل',MessageCircle],['marketing','التسويق',Megaphone],['reports','التقارير',BarChart3],['team','الفريق والصلاحيات',UserCog]
];

function Sidebar({view,setView,collapsed,setCollapsed}){return <aside className={`sidebar ${collapsed?'collapsed':''}`}><div className="side-top"><Logo compact={collapsed}/><button className="collapse-btn" onClick={()=>setCollapsed(!collapsed)}><Menu/></button></div><div className="clinic-switch"><span className="clinic-avatar">CM</span>{!collapsed&&<div><b>مركز كلينيكا الطبي</b><small>فرع مدينة نصر</small></div>}{!collapsed&&<ChevronDown/>}</div><nav>{navItems.map(([key,label,I])=><button className={view===key?'active':''} onClick={()=>setView(key)} key={key}><I/>{!collapsed&&<span>{label}</span>}{key==='messages'&&!collapsed&&<em>3</em>}</button>)}</nav><div className="side-footer"><button><Settings/>{!collapsed&&'الإعدادات'}</button><button><LogOut/>{!collapsed&&'تسجيل الخروج'}</button></div></aside>}

function AppHeader({view,setView}){const title=navItems.find(x=>x[0]===view)?.[1]||'لوحة التحكم';return <header className="app-header"><div><span className="mobile-kicker">مركز كلينيكا الطبي</span><h1>{title}</h1></div><div className="app-actions"><div className="global-search"><Search/><input placeholder="ابحث عن مريض أو موعد..."/></div><button className="notification"><Bell/><i></i></button><button className="user-menu"><span>دس</span><div><b>د. سلمى الشريف</b><small>طبيب مدير</small></div><ChevronDown/></button></div></header>}

function StatCard({icon:I,label,value,delta,tone}){return <article className="stat-card"><div className="stat-top"><IconBadge tone={tone}><I/></IconBadge><span className={delta.startsWith('+')?'up':'neutral'}>{delta}</span></div><b>{value}</b><p>{label}</p></article>}

function Dashboard({setView}){return <div className="dashboard-page"><div className="welcome-banner"><div><span>صباح الخير، د. سلمى 👋</span><h2>العيادة جاهزة ليوم جديد من الرعاية</h2><p>لديك 12 موعدًا اليوم، و3 مرضى يحتاجون مراجعة خطط المتابعة.</p></div><button onClick={()=>setView('appointments')}><Plus/>موعد جديد</button></div><div className="stats-grid"><StatCard icon={CalendarCheck} label="مواعيد اليوم" value="12" delta="+8%" tone="blue"/><StatCard icon={UsersRound} label="مرضى في الانتظار" value="04" delta="الآن" tone="orange"/><StatCard icon={ClipboardCheck} label="متابعات مطلوبة" value="07" delta="3 عاجلة" tone="coral"/><StatCard icon={UserRound} label="مرضى هذا الشهر" value="186" delta="+12%" tone="teal"/></div><div className="dash-grid"><section className="panel schedule-panel"><PanelHead title="جدول اليوم" action="عرض التقويم" onClick={()=>setView('appointments')}/><div className="appointments-list">{appointments.map((a,i)=><div className="appointment-row" key={i}><span className="time">{a.time}</span><span className="avatar sm">{a.avatar}</span><div className="appointment-main"><b>{a.patient}</b><small>{a.type} · {a.doctor}</small></div><Status text={a.status}/><button className="more-btn"><MoreHorizontal/></button></div>)}</div></section><section className="panel chart-panel"><PanelHead title="حركة الحجوزات" action="آخر 7 أيام"/><div className="chart"><div className="chart-y"><span>40</span><span>30</span><span>20</span><span>10</span><span>0</span></div><div className="bars">{[48,68,57,82,72,91,76].map((h,i)=><div key={i}><i style={{height:`${h}%`}} className={i===5?'hot':''}></i><span>{['سبت','أحد','اثنين','ثلاثاء','أربعاء','خميس','جمعة'][i]}</span></div>)}</div></div><div className="chart-legend"><span><i className="teal-dot"></i>حجز مؤكد</span><span><i className="coral-dot"></i>إلغاء</span></div></section><section className="panel queue-panel"><PanelHead title="الطابور الحالي" action="إدارة الطابور"/><div className="queue-now"><div><span>رقم الدور</span><b>08</b></div><i></i><div><span>متوسط الانتظار</span><b>14 <small>دقيقة</small></b></div></div>{[['09','نور علي','في الانتظار'],['10','أحمد حسن','تم تسجيل الوصول'],['11','منى محمود','موعدها قريب']].map(x=><div className="queue-row" key={x[0]}><b>{x[0]}</b><span>{x[1]}<small>{x[2]}</small></span><ChevronLeft/></div>)}</section><section className="panel alerts-panel"><PanelHead title="تنبيهات المتابعة" action="عرض الكل" onClick={()=>setView('followup')}/>{[['سارة سامح','قراءة سكر مرتفعة','منذ 12 دقيقة','critical'],['محمود رجب','لم يسجل الضغط اليوم','منذ ساعتين','warning'],['منى محمود','رفعت تحليلًا جديدًا','منذ 4 ساعات','info']].map(([n,t,d,c])=><div className={`alert-row ${c}`} key={n}><span><Activity/></span><div><b>{n}</b><p>{t}</p></div><small>{d}</small></div>)}</section></div></div>}

function PanelHead({title,action,onClick}){return <div className="panel-head"><h3>{title}</h3><button onClick={onClick}>{action}<ChevronLeft/></button></div>}
function Status({text}){const c=text==='حضر'?'success':text==='في الانتظار'?'warning':text==='مؤكد'?'info':'muted';return <span className={`status ${c}`}>{text}</span>}

function Appointments(){const [filter,setFilter]=useState('الكل');return <div><div className="page-toolbar"><div className="date-nav"><button><ChevronLeft/></button><div><b>الأربعاء، 17 سبتمبر</b><small>5 مواعيد · 3 أطباء</small></div><button><ChevronLeft className="flip"/></button></div><div><button className="outline-btn"><Download/>تصدير</button><button className="primary-btn"><Plus/>موعد جديد</button></div></div><div className="calendar-layout"><section className="panel calendar-panel"><div className="calendar-top"><div className="segmented">{['اليوم','أسبوع','شهر'].map(x=><button className={x==='اليوم'?'active':''}>{x}</button>)}</div><div className="calendar-filters">{['الكل','د. سلمى','د. عمر','د. مريم'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div></div><div className="day-schedule">{['08:00','09:00','10:00','11:00','12:00','01:00','02:00'].map((t,i)=><div className="hour-row"><time>{t}</time><div className="hour-line"></div>{i===1&&<div className="event teal-event" style={{right:'17%',width:'31%'}}><b>أحمد حسن</b><span>متابعة · د. سلمى</span></div>}{i===2&&<div className="event blue-event" style={{right:'50%',width:'28%'}}><b>نور علي</b><span>كشف جديد · د. عمر</span></div>}{i===3&&<div className="event coral-event" style={{right:'25%',width:'34%'}}><b>منى محمود</b><span>تحاليل · د. سلمى</span></div>}</div>)}</div></section><aside className="panel waitlist"><PanelHead title="قائمة الانتظار" action="+ إضافة"/>{patients.slice(0,3).map((p,i)=><div className="wait-person"><span className="avatar sm">{p.name.split(' ').map(x=>x[0]).join('')}</span><div><b>{p.name}</b><small>{p.condition}</small></div><button>إضافة للجدول</button></div>)}<div className="no-show"><AlarmClock/><div><b>توقع عدم الحضور</b><p>موعد سارة سامح لديه احتمالية تأخر متوسطة بناءً على آخر الزيارات.</p></div></div></aside></div></div>}

function Patients({setView}){const [q,setQ]=useState('');const shown=patients.filter(p=>p.name.includes(q)||p.id.toLowerCase().includes(q.toLowerCase()));return <div><div className="page-toolbar"><div className="search-large"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث بالاسم أو رقم الملف أو الهاتف"/></div><div><button className="outline-btn"><Upload/>استيراد</button><button className="primary-btn"><Plus/>مريض جديد</button></div></div><section className="panel data-panel"><div className="table-filters"><div className="filter-chips"><button className="active">كل المرضى <b>248</b></button><button>متابعة نشطة <b>64</b></button><button>تحتاج مراجعة <b>7</b></button></div><button className="outline-btn small">فلترة متقدمة <ChevronDown/></button></div><table><thead><tr><th>المريض</th><th>رقم الملف</th><th>الحالة</th><th>آخر زيارة</th><th>المتابعة القادمة</th><th>درجة المتابعة</th><th></th></tr></thead><tbody>{shown.map(p=><tr onClick={()=>setView('patient-file')}><td><div className="patient-cell"><span className="avatar">{p.name.split(' ').map(x=>x[0]).join('')}</span><span><b>{p.name}</b><small>{p.age} سنة · {p.phone}</small></span></div></td><td><code>{p.id}</code></td><td>{p.condition}</td><td>{p.last}</td><td>{p.next}</td><td><span className={`risk ${p.risk}`}>{p.risk}</span></td><td><button className="more-btn"><MoreHorizontal/></button></td></tr>)}</tbody></table></section></div>}

function PatientFile(){const [tab,setTab]=useState('الملخص');return <div><div className="patient-header-card"><div className="patient-identity"><span className="avatar xl">أح</span><div><span className="patient-id">CL-2041</span><h2>أحمد حسن عبد الله</h2><p>46 سنة · ذكر · 010 2468 1357</p></div></div><div className="patient-tags"><span className="tag red">حساسية بنسلين</span><span className="tag orange">ضغط مرتفع</span><span className="tag blue">متابعة قلب</span></div><div className="patient-actions"><button className="outline-btn"><MessageCircle/>رسالة</button><button className="primary-btn"><Plus/>زيارة جديدة</button></div></div><div className="record-tabs">{['الملخص','الزيارات','القياسات','التحاليل والأشعة','الوصفات','المرفقات'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div><div className="record-layout"><main><section className="panel clinical-summary"><PanelHead title="الملخص الطبي" action="تعديل"/><div className="clinical-grid"><div><small>فصيلة الدم</small><b>O+</b></div><div><small>الطول</small><b>176 سم</b></div><div><small>الوزن</small><b>84 كجم</b></div><div><small>ضغط الدم</small><b>138/88</b></div><div><small>السكر</small><b>104 mg/dL</b></div><div><small>آخر نبض</small><b>78 bpm</b></div></div></section><section className="panel timeline-panel"><PanelHead title="الخط الزمني السريري" action="عرض كامل"/><div className="timeline"><TimelineItem icon={Stethoscope} tone="teal" date="اليوم · 09:00 ص" title="زيارة متابعة ضغط الدم" text="تمت مراجعة قراءات الأسبوع، تعديل الجرعة، وطلب تحليل وظائف كلى." tag="د. سلمى الشريف"/><TimelineItem icon={TestTube2} tone="purple" date="15 سبتمبر" title="نتائج تحاليل جديدة" text="صورة دم كاملة، وظائف كلى، ونسبة الدهون. النتائج ضمن الحدود المقبولة." tag="معمل كلينيكا"/><TimelineItem icon={Pill} tone="blue" date="2 سبتمبر" title="وصفة دوائية" text="Amlodipine 5mg مرة يوميًا لمدة 30 يومًا." tag="د. سلمى الشريف"/><TimelineItem icon={FileText} tone="orange" date="19 أغسطس" title="تقرير موجات صوتية" text="كفاءة عضلة القلب جيدة، ولا توجد تغيرات ملحوظة." tag="مرفق PDF"/></div></section></main><aside><section className="panel plan-card"><div className="plan-head"><span><ClipboardList/></span><div><b>خطة المتابعة الحالية</b><small>بدأت 17 سبتمبر</small></div></div><div className="progress-ring"><div><b>72%</b><span>التزام</span></div></div><ul><li><Check/>قياس الضغط صباحًا ومساءً</li><li><Check/>دواء الضغط بعد الإفطار</li><li><Clock3/>المشي 30 دقيقة</li><li><Clock3/>رفع تحليل وظائف الكلى</li></ul><button className="outline-btn full">فتح خطة المتابعة</button></section><section className="panel care-team"><PanelHead title="فريق الرعاية" action="إدارة"/><div className="care-person"><img src={doctors[0].image}/><span><b>د. سلمى الشريف</b><small>الطبيب المسؤول</small></span></div><div className="care-person"><span className="avatar sm">مس</span><span><b>مها سعيد</b><small>منسقة المتابعة</small></span></div></section></aside></div></div>}

function TimelineItem({icon:I,tone,date,title,text,tag}){return <div className="timeline-item"><IconBadge tone={tone}><I/></IconBadge><div><small>{date}</small><h4>{title}</h4><p>{text}</p><span>{tag}</span></div></div>}

function FollowUp(){const [selected,setSelected]=useState(0);const cards=[['سارة سامح','سكري نوع 2','قراءة مرتفعة','critical','164 mg/dL'],['أحمد حسن','ضغط مرتفع','مستقر','stable','138/88'],['منى محمود','متابعة قلب','ملتزمة','stable','78 bpm'],['محمود رجب','ضغط مرتفع','متأخر في التسجيل','warning','—']];return <div><div className="page-toolbar"><div><h2 className="subpage-title">متابعة المرضى عن بُعد</h2><p>راجع القياسات والأعراض والالتزام بالخطة بين الزيارات.</p></div><button className="primary-btn"><Plus/>خطة متابعة</button></div><div className="follow-layout"><aside className="panel follow-list"><div className="search-mini"><Search/><input placeholder="ابحث عن مريض"/></div>{cards.map((c,i)=><button className={selected===i?'active':''} onClick={()=>setSelected(i)}><span className="avatar sm">{c[0].split(' ').map(x=>x[0]).join('')}</span><span><b>{c[0]}</b><small>{c[1]}</small></span><em className={c[3]}>{c[2]}</em></button>)}</aside><main className="follow-detail"><section className="panel follow-hero"><div><span className="avatar lg">سس</span><span><h3>سارة سامح</h3><p>سكري نوع 2 · خطة نشطة منذ 42 يومًا</p></span></div><button className="outline-btn"><MessageCircle/>إرسال رسالة</button></section><div className="metric-grid"><Metric title="سكر الدم" value="164" unit="mg/dL" note="أعلى من الهدف" tone="red"/><Metric title="الوزن" value="78.4" unit="كجم" note="-1.2 هذا الشهر" tone="green"/><Metric title="الالتزام بالدواء" value="86" unit="%" note="جيد" tone="blue"/></div><section className="panel measurement-chart"><PanelHead title="قراءات سكر الدم" action="آخر 14 يومًا"/><div className="line-visual"><div className="target-band">النطاق المستهدف</div><svg viewBox="0 0 700 210" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ef6f61" stopOpacity=".26"/><stop offset="1" stopColor="#ef6f61" stopOpacity="0"/></linearGradient></defs><path d="M0 160 C70 140,90 95,145 118 S240 155,290 95 S370 75,420 105 S500 150,550 80 S635 60,700 42 L700 210 L0 210Z" fill="url(#area)"/><path d="M0 160 C70 140,90 95,145 118 S240 155,290 95 S370 75,420 105 S500 150,550 80 S635 60,700 42" fill="none" stroke="#ef6f61" strokeWidth="4"/><circle cx="700" cy="42" r="7" fill="#ef6f61"/></svg><div className="chart-days"><span>4 سبتمبر</span><span>7 سبتمبر</span><span>10 سبتمبر</span><span>13 سبتمبر</span><span>اليوم</span></div></div></section><section className="panel tasks-panel"><PanelHead title="مهام اليوم" action="تعديل الخطة"/><div className="task-row done"><span><Check/></span><div><b>قياس السكر قبل الإفطار</b><small>تم التسجيل · 08:12 ص</small></div><em>164 mg/dL</em></div><div className="task-row"><span><Pill/></span><div><b>جرعة الدواء الصباحية</b><small>موعدها 09:00 ص</small></div><button>تذكير</button></div><div className="task-row"><span><Activity/></span><div><b>المشي لمدة 20 دقيقة</b><small>قبل 08:00 م</small></div><button>تذكير</button></div></section></main></div></div>}

function Metric({title,value,unit,note,tone}){return <article className={`metric-card ${tone}`}><small>{title}</small><b>{value}<em>{unit}</em></b><span>{note}</span></article>}

function Messages(){return <div className="messages-shell"><section className="conversation-list"><div className="messages-title"><h2>الرسائل</h2><button><Plus/></button></div><div className="search-mini"><Search/><input placeholder="ابحث في المحادثات"/></div>{[['أحمد حسن','تم رفع التحليل المطلوب','10:32','2'],['سارة سامح','قراءة السكر اليوم مرتفعة','09:18','1'],['منى محمود','شكرًا يا دكتورة','أمس',''],['محمود رجب','هل أستمر على نفس الجرعة؟','أمس','']].map((c,i)=><button className={i===0?'active':''}><span className="avatar sm">{c[0].split(' ').map(x=>x[0]).join('')}</span><span><b>{c[0]}</b><small>{c[1]}</small></span><em>{c[2]}{c[3]&&<i>{c[3]}</i>}</em></button>)}</section><section className="chat-panel"><div className="chat-head"><div><span className="avatar">أح</span><span><b>أحمد حسن</b><small><i></i> متصل الآن · ملف CL-2041</small></span></div><button><Phone/></button><button><MoreHorizontal/></button></div><div className="chat-body"><div className="day-separator">اليوم</div><div className="bubble patient">صباح الخير يا دكتورة، رفعت تحليل وظائف الكلى المطلوب.<small>10:28 ص</small></div><div className="attachment-message"><FileText/><div><b>Kidney-functions.pdf</b><small>PDF · 1.8 MB</small></div><button><Download/></button></div><div className="bubble doctor">وصل يا أستاذ أحمد، راجعت النتائج وهي مطمئنة. استمر على الجرعة الحالية وسجل الضغط مساءً.<small>10:31 ص ✓✓</small></div><div className="bubble patient">تمام، شكرًا لحضرتك.<small>10:32 ص</small></div></div><div className="chat-input"><button><Plus/></button><input placeholder="اكتب رسالة..."/><button className="send"><ArrowLeft/></button></div></section><aside className="chat-info"><span className="avatar xl">أح</span><h3>أحمد حسن</h3><p>46 سنة · متابعة قلب وضغط</p><div className="mini-info"><span><small>آخر زيارة</small><b>اليوم</b></span><span><small>المتابعة</small><b>نشطة</b></span></div><button className="outline-btn full"><FileHeart/>فتح الملف الطبي</button><h4>ملفات المحادثة</h4><div className="file-tile"><FileText/><span><b>Kidney-functions.pdf</b><small>اليوم</small></span></div></aside></div>}

function Marketing(){const videos=[['ارتفاع ضغط الدم','تم النشر','12.4K','82%'],['متى تزور طبيب القلب؟','جاهز للنشر','—','—'],['3 أخطاء في قياس الضغط','قيد المونتاج','—','65%'],['هل الملح ممنوع تمامًا؟','سيناريو معتمد','—','20%']];return <div><div className="marketing-header"><div><span className="section-kicker">مركز المحتوى</span><h2>خطة د. سلمى الشريف</h2><p>سبتمبر 2026 · طب القلب والأوعية</p></div><div className="plan-counter"><Video/><span><b>3 من 4</b><small>فيديوهات هذا الشهر</small></span></div><button className="primary-btn"><Plus/>فكرة محتوى</button></div><div className="marketing-stats"><StatCard icon={Video} label="تم النشر" value="01" delta="هذا الشهر" tone="teal"/><StatCard icon={Zap} label="إجمالي المشاهدات" value="12.4K" delta="+18%" tone="blue"/><StatCard icon={MessageCircle} label="تفاعل" value="684" delta="+24%" tone="coral"/><StatCard icon={CalendarCheck} label="التالي" value="19 Sep" delta="جاهز" tone="orange"/></div><section className="panel content-board"><div className="board-head"><div><h3>مسار إنتاج المحتوى</h3><p>من الفكرة حتى النشر وقياس الأداء.</p></div><div className="avatars-stack"><span>م</span><span>أ</span><span>س</span><b>فريق المحتوى</b></div></div><div className="kanban">{[['أفكار','2'],['كتابة ومراجعة','1'],['إنتاج','1'],['تم النشر','1']].map((col,ci)=><div className="kanban-col"><h4>{col[0]}<span>{col[1]}</span></h4>{videos.filter((_,i)=>i%4===ci).map((v,i)=><article className="content-card"><div className="content-thumb">{ci===3?<img src="https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=500&q=80"/>:<Video/>}<span>{v[1]}</span></div><h5>{v[0]}</h5><p>ريل تعليمي · 45 ثانية</p><div><span><BarChart3/>{v[2]}</span><span>إنجاز {v[3]}</span></div></article>)}</div>)}</div></section></div>}

function Reports(){return <div><div className="page-toolbar"><div><h2 className="subpage-title">تقارير التشغيل</h2><p>نظرة موحدة على الحجوزات والأداء والمتابعة.</p></div><div><button className="outline-btn">هذا الشهر <ChevronDown/></button><button className="primary-btn"><Download/>تصدير التقرير</button></div></div><div className="stats-grid"><StatCard icon={CalendarCheck} label="إجمالي الحجوزات" value="462" delta="+13%" tone="blue"/><StatCard icon={Check} label="نسبة الحضور" value="88%" delta="+4%" tone="teal"/><StatCard icon={X} label="الإلغاءات" value="7.2%" delta="-2%" tone="coral"/><StatCard icon={Activity} label="خطط متابعة نشطة" value="64" delta="+9" tone="purple"/></div><div className="report-grid"><section className="panel large-chart"><PanelHead title="الحجوزات والحضور" action="آخر 30 يومًا"/><div className="area-placeholder"><svg viewBox="0 0 900 300" preserveAspectRatio="none"><defs><linearGradient id="tealArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#0d8f8b" stopOpacity=".24"/><stop offset="1" stopColor="#0d8f8b" stopOpacity="0"/></linearGradient></defs><path d="M0 250 C100 235,120 170,210 188 S330 220,390 135 S520 110,590 148 S710 190,780 85 S850 72,900 42 L900 300 L0 300Z" fill="url(#tealArea)"/><path d="M0 250 C100 235,120 170,210 188 S330 220,390 135 S520 110,590 148 S710 190,780 85 S850 72,900 42" stroke="#0d8f8b" strokeWidth="4" fill="none"/></svg></div></section><section className="panel sources"><PanelHead title="مصادر الحجز" action="عرض التفاصيل"/>{[['الموقع',42,'#07847f'],['الاستقبال',31,'#4f7ee8'],['إعادة حجز',18,'#ed7c64'],['إحالة',9,'#a273d6']].map(x=><div className="source-row"><span>{x[0]}<b>{x[1]}%</b></span><div><i style={{width:`${x[1]}%`,background:x[2]}}></i></div></div>)}</section><section className="panel doctor-performance"><PanelHead title="أداء الدكاترة" action="عرض الكل"/>{doctors.map((d,i)=><div className="doctor-perf"><img src={d.image}/><span><b>{d.name}</b><small>{[168,142,119][i]} حجز · حضور {[91,87,89][i]}%</small></span><div><b>{d.rating}</b><Star fill="currentColor"/></div></div>)}</section><section className="panel insights"><div className="insight-icon"><Sparkles/></div><h3>ملخص ذكي للأداء</h3><p>زادت حجوزات الموقع 13% هذا الشهر. يوم الخميس هو الأعلى ضغطًا، بينما الثلاثاء 1–3 مساءً لديه سعة غير مستغلة.</p><button>عرض توصيات الجدول <ArrowLeft/></button></section></div></div>}

function Team(){return <div><div className="page-toolbar"><div><h2 className="subpage-title">الفريق والصلاحيات</h2><p>تحكم في وصول كل عضو وسجّل كل التغييرات الحساسة.</p></div><button className="primary-btn"><Plus/>إضافة عضو</button></div><div className="team-layout"><section className="panel team-table"><table><thead><tr><th>العضو</th><th>الدور</th><th>الفرع</th><th>الحالة</th><th>آخر نشاط</th><th></th></tr></thead><tbody>{[['د. سلمى الشريف','طبيب مدير','مدينة نصر','نشط','الآن'],['د. عمر منصور','طبيب','مدينة نصر','نشط','منذ 8 د'],['مها سعيد','منسقة متابعة','كل الفروع','نشط','منذ 15 د'],['نجلاء أحمد','استقبال','مصر الجديدة','متوقف','أمس']].map((x,i)=><tr><td><div className="patient-cell"><span className="avatar">{x[0].replace('د. ','').split(' ').map(s=>s[0]).join('')}</span><span><b>{x[0]}</b><small>{i<2?'doctor@clinica.demo':'staff@clinica.demo'}</small></span></div></td><td>{x[1]}</td><td>{x[2]}</td><td><span className={`status ${x[3]==='نشط'?'success':'muted'}`}>{x[3]}</span></td><td>{x[4]}</td><td><MoreHorizontal/></td></tr>)}</tbody></table></section><aside><section className="panel security-card"><span><ShieldCheck/></span><h3>حماية بيانات المرضى</h3><p>الصلاحيات مقسمة حسب الدور، وكل مشاهدة أو تعديل للملف الطبي تُسجل تلقائيًا.</p><button className="outline-btn full">مراجعة الصلاحيات</button></section><section className="panel audit-card"><PanelHead title="آخر الأنشطة" action="سجل كامل"/>{[['مها سعيد','حدّثت خطة متابعة أحمد حسن','منذ 8 د'],['د. عمر','أضاف وصفة لنور علي','منذ 20 د'],['نجلاء','أعادت جدولة موعد','منذ ساعة']].map(x=><div><span className="avatar sm">{x[0][0]}</span><p><b>{x[0]}</b> {x[1]}<small>{x[2]}</small></p></div>)}</section></aside></div></div>}

function PatientPortal({onBack}){return <div className="patient-portal"><header><Logo/><nav><button className="active">الرئيسية</button><button>حجوزاتي</button><button>ملفي الطبي</button><button>المتابعة</button><button>الرسائل</button></nav><div><button className="notification"><Bell/><i></i></button><span className="avatar">أح</span><button onClick={onBack} className="outline-btn small">العودة للموقع</button></div></header><main><section className="patient-welcome"><div><span>أهلًا يا أحمد 👋</span><h1>صحتك اليوم في المسار الصحيح</h1><p>تابع خطتك وسجل قياساتك وتواصل مع فريق الرعاية بسهولة.</p></div><div className="next-visit"><CalendarCheck/><span><small>الموعد القادم</small><b>السبت، 28 سبتمبر · 10:30 ص</b><p>د. سلمى الشريف · فرع مدينة نصر</p></span><button>تفاصيل الموعد</button></div></section><div className="patient-dashboard-grid"><section className="portal-main"><div className="portal-stats"><article><IconBadge tone="teal"><Activity/></IconBadge><span><small>آخر ضغط</small><b>138/88</b><em>مستقر</em></span></article><article><IconBadge tone="blue"><Pill/></IconBadge><span><small>التزام الدواء</small><b>92%</b><em>ممتاز</em></span></article><article><IconBadge tone="orange"><ClipboardCheck/></IconBadge><span><small>مهام اليوم</small><b>2 من 3</b><em>متبقي مهمة</em></span></article></div><section className="portal-card today-plan"><div className="portal-card-head"><h3>خطة اليوم</h3><span>الأربعاء، 17 سبتمبر</span></div>{[['قياس الضغط صباحًا','08:15 ص','138/88','done'],['تناول الدواء بعد الإفطار','09:00 ص','تم','done'],['المشي لمدة 30 دقيقة','07:00 م','لم يكتمل','']].map(x=><div className={`patient-task ${x[3]}`}><span>{x[3]?<Check/>:<Clock3/>}</span><div><b>{x[0]}</b><small>{x[1]}</small></div><em>{x[2]}</em></div>)}</section><section className="portal-card readings-card"><div className="portal-card-head"><h3>سجل القياسات</h3><button>+ تسجيل قياس</button></div><div className="mini-chart"><svg viewBox="0 0 800 180" preserveAspectRatio="none"><path d="M0 130 C90 145,120 80,210 100 S350 145,430 80 S570 60,650 95 S740 75,800 48" stroke="#07847f" strokeWidth="4" fill="none"/></svg></div></section></section><aside className="portal-side"><section className="doctor-contact"><img src={doctors[0].image}/><div><small>طبيبتك المسؤولة</small><h3>د. سلمى الشريف</h3><p>طب القلب والأوعية</p></div><button><MessageCircle/>إرسال رسالة</button></section><section className="portal-card quick-files"><div className="portal-card-head"><h3>آخر الملفات</h3><button>عرض الكل</button></div><div><FileText/><span><b>وظائف الكلى.pdf</b><small>تمت المراجعة</small></span><Check/></div><div><FileText/><span><b>قياسات سبتمبر</b><small>تم التحديث اليوم</small></span><ChevronLeft/></div></section><section className="health-tip"><Sparkles/><div><b>نصيحة اليوم</b><p>قلل الملح ودوّن ضغطك في نفس الموعد يوميًا لقراءات أدق.</p></div></section></aside></div></main></div>}

function AppShell({initial='dashboard',onExit}){const [view,setView]=useState(initial);const [collapsed,setCollapsed]=useState(false);if(view==='patient')return <PatientPortal onBack={()=>setView('dashboard')}/>;let content={dashboard:<Dashboard setView={setView}/>,appointments:<Appointments/>,patients:<Patients setView={setView}/>, 'patient-file':<PatientFile/>,followup:<FollowUp/>,messages:<Messages/>,marketing:<Marketing/>,reports:<Reports/>,team:<Team/>}[view]||<Dashboard setView={setView}/>;return <div className="app-shell"><Sidebar view={view} setView={setView} collapsed={collapsed} setCollapsed={setCollapsed}/><div className="app-main"><AppHeader view={view} setView={setView}/><div className="demo-bar"><span><Sparkles/>نسخة عرض تجريبية ببيانات غير حقيقية</span><div><button onClick={()=>setView('patient')}>بوابة المريض</button><button onClick={onExit}>العودة للموقع</button></div></div><div className="app-content">{content}</div></div></div>}

export default function App(){const [mode,setMode]=useState('landing');const open=(v)=>setMode(v==='patient'?'patient':v);if(mode==='landing')return <Landing onOpen={open}/>;if(mode==='patient')return <PatientPortal onBack={()=>setMode('landing')}/>;return <AppShell initial={mode} onExit={()=>setMode('landing')}/>}
